Add .editorconfig and replace spaces with tabs

diff --git a/bin/imds b/bin/imds
--- a/bin/imds
+++ b/bin/imds
@@ -1,5 +1,5 @@
 #!/bin/sh
-# vim:set ts=4 et ft=sh:
+# vim:set ft=sh:
 
 # Tiny Cloud - Instance MetaData Service client
 
@@ -9,43 +9,43 @@
 . "$LIBDIR/tiny-cloud/common"
 
 if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
-    cat <<EOT
-Usage: imds [-h] { -e | +e | +n | +s | +t | @<alias> | <imds-path> } ...
-  -h           : help
-  -e / +e      : ignore / catch errors
-  +n / +s / +t : insert newline / space / tab
-  <alias> :-
-    hostname       : instance hostname
-    local-hostname : instance local hostname
-    ssh-keys       : instance SSH keys
-    userdata       : instance user data
-    nics           : instance NICs
-    nic:<iface>[,<nic-key> ...] : specific NIC interface
-      <iface>   : network interface (i.e. eth1)
-      <nic-key> :- { -e | +e | +n | +s | +t | @<nic-alias> | <nic-path> }
-        <nic-alias> :-
-          mac         : mac address
-          ipv4        : ipv4 address(es)
-          ipv6        : ipv6 address(es)
-          ipv4-net    : subnet ipv4 network(s)
-          ipv6-net    : subnet ipv6 network(s)
-          ipv4-prefix : delegated ipv4 CIDR(s)
-          ipv6-prefix : delegated ipv6 CIDR(s)
-EOT
-    exit 0
+	cat <<-EOT
+		Usage: imds [-h] { -e | +e | +n | +s | +t | @<alias> | <imds-path> } ...
+		  -h           : help
+		  -e / +e      : ignore / catch errors
+		  +n / +s / +t : insert newline / space / tab
+		  <alias> :-
+		    hostname       : instance hostname
+		    local-hostname : instance local hostname
+		    ssh-keys       : instance SSH keys
+		    userdata       : instance user data
+		    nics           : instance NICs
+		    nic:<iface>[,<nic-key> ...] : specific NIC interface
+		      <iface>   : network interface (i.e. eth1)
+		      <nic-key> :- { -e | +e | +n | +s | +t | @<nic-alias> | <nic-path> }
+		        <nic-alias> :-
+		          mac         : mac address
+		          ipv4        : ipv4 address(es)
+		          ipv6        : ipv6 address(es)
+		          ipv4-net    : subnet ipv4 network(s)
+		          ipv6-net    : subnet ipv6 network(s)
+		          ipv4-prefix : delegated ipv4 CIDR(s)
+		          ipv6-prefix : delegated ipv6 CIDR(s)
+	EOT
+	exit 0
 fi
 
 ### cloud-specific variables/functions
 
 unset \
-    IMDS_HEADER \
-    IMDS_URI \
-    IMDS_QUERY
+	IMDS_HEADER \
+	IMDS_URI \
+	IMDS_QUERY
 unset -f \
-    _imds_token \
-    _imds_header \
-    _imds_nic_index \
-        2>/dev/null	|| true
+	_imds_token \
+	_imds_header \
+	_imds_nic_index \
+		2>/dev/null || true
 
 ### default variables/functions
 
@@ -67,19 +67,19 @@ IMDS_IPV4_PREFIX="ipv4-prefix"
 IMDS_IPV6_PREFIX="ipv6-prefix"
 
 _imds() {
-    wget --quiet --timeout 1 --output-document - \
-        --header "$(_imds_header)" \
-        "http://$IMDS_ENDPOINT/$IMDS_URI/$1$IMDS_QUERY"
+	wget --quiet --timeout 1 --output-document - \
+		--header "$(_imds_header)" \
+		"http://$IMDS_ENDPOINT/$IMDS_URI/$1$IMDS_QUERY"
 }
 
 _imds_userdata() { _imds "$IMDS_USERDATA"; }
 
 _imds_ssh_keys() {
-    local key
-    for key in $(_imds "$IMDS_SSH_KEYS"); do
-        _imds "$IMDS_SSH_KEYS/${key%=*}/openssh-key"
-        echo
-    done | sort -u
+	local key
+	for key in $(_imds "$IMDS_SSH_KEYS"); do
+		_imds "$IMDS_SSH_KEYS/${key%=*}/openssh-key"
+		echo
+	done | sort -u
 }
 
 _imds_nic_index() { cat "/sys/class/net/$1/address"; }
@@ -87,71 +87,71 @@ _imds_nic_index() { cat "/sys/class/net/$1/address"; }
 ### load cloud-specific variables and functions
 
 if [ ! -d "$LIBDIR/tiny-cloud/cloud/$CLOUD" ]; then
-    echo "ERROR: Unknown Cloud '$CLOUD'" >&2
+	echo "ERROR: Unknown Cloud '$CLOUD'" >&2
 fi
 . "$LIBDIR/tiny-cloud/cloud/$CLOUD/imds"
 
 ### non-overrideable functions
 
 imds() {
-    local cmd args key rv err=1
-    while [ -n "$1" ]; do
-        cmd=_imds
-        args=
-        key="$1"; shift
-        case $key in
-            # error handling
-            -e) err=0; continue ;;          # ignore
-            +e) err=1; continue ;;          # return
-            # TODO: retry/deadline
-            # output control
-            +n) printf "\n"; continue ;;           # insert newline
-            +s) printf " "; continue ;;    # insert space
-            +t) printf "\t"; continue ;;  # insert tab
-            # key aliasing
-            @hostname)        args="$IMDS_HOSTNAME" ;;
-            @local-hostname)  args="$IMDS_LOCAL_HOSTNAME" ;;
-            @ssh-keys)        cmd=_imds_ssh_keys ;;
-            @userdata)        cmd=_imds_userdata ;;
-            @nics)            args="$IMDS_NICS" ;;
-            @nic:*)
-                cmd=imds
-                args=$(_imds_nic_args $(echo "${key#@nic:}" | tr , ' '))
-                ;;
-            # use key verbatim
-            *) args="$key" ;;
-        esac
-        # TODO: retry/deadline
-        "$cmd" $args
-        rv=$?
-        [ $err -eq 0 ] && continue
-        [ $rv = "0" ] || return $rv
-    done
+	local cmd args key rv err=1
+	while [ -n "$1" ]; do
+		cmd=_imds
+		args=
+		key="$1"; shift
+		case $key in
+			# error handling
+			-e) err=0; continue ;;		  # ignore
+			+e) err=1; continue ;;		  # return
+			# TODO: retry/deadline
+			# output control
+			+n) printf "\n"; continue ;;		   # insert newline
+			+s) printf " "; continue ;;	# insert space
+			+t) printf "\t"; continue ;;  # insert tab
+			# key aliasing
+			@hostname)		args="$IMDS_HOSTNAME" ;;
+			@local-hostname)  args="$IMDS_LOCAL_HOSTNAME" ;;
+			@ssh-keys)		cmd=_imds_ssh_keys ;;
+			@userdata)		cmd=_imds_userdata ;;
+			@nics)			args="$IMDS_NICS" ;;
+			@nic:*)
+				cmd=imds
+				args=$(_imds_nic_args $(echo "${key#@nic:}" | tr , ' '))
+				;;
+			# use key verbatim
+			*) args="$key" ;;
+		esac
+		# TODO: retry/deadline
+		"$cmd" $args
+		rv=$?
+		[ $err -eq 0 ] && continue
+		[ $rv = "0" ] || return $rv
+	done
 }
 
 _imds_nic_args() {
-    local key nic
-    nic=$(_imds_nic_index "$1") || return 1
-    if [ -z "$2" ]; then
-        echo "$IMDS_NICS/$nic"
-        return
-    fi
-    while [ -n "$2" ]; do
-        key="$2"
-        shift
-        case "$key" in
-            @mac)           key="$IMDS_MAC" ;;
-            @ipv4)          key="$IMDS_IPV4" ;;
-            @ipv6)          key="$IMDS_IPV6" ;;
-            @ipv4-net)      key="$IMDS_IPV4_NET" ;;
-            @ipv6-net)      key="$IMDS_IPV6_NET" ;;
-            @ipv4-prefix)   key="$IMDS_IPV4_PREFIX" ;;
-            @ipv6-prefix)   key="$IMDS_IPV6_PREFIX" ;;
-            # error/output control passthrough
-            -e|+[enst])     printf "$key\n"; continue ;;
-        esac
-        printf "$IMDS_NICS/$nic/$key\n"
-    done
+	local key nic
+	nic=$(_imds_nic_index "$1") || return 1
+	if [ -z "$2" ]; then
+		echo "$IMDS_NICS/$nic"
+		return
+	fi
+	while [ -n "$2" ]; do
+		key="$2"
+		shift
+		case "$key" in
+			@mac)		   key="$IMDS_MAC" ;;
+			@ipv4)		  key="$IMDS_IPV4" ;;
+			@ipv6)		  key="$IMDS_IPV6" ;;
+			@ipv4-net)	  key="$IMDS_IPV4_NET" ;;
+			@ipv6-net)	  key="$IMDS_IPV6_NET" ;;
+			@ipv4-prefix)   key="$IMDS_IPV4_PREFIX" ;;
+			@ipv6-prefix)   key="$IMDS_IPV6_PREFIX" ;;
+			# error/output control passthrough
+			-e|+[enst])	 printf "$key\n"; continue ;;
+		esac
+		printf "$IMDS_NICS/$nic/$key\n"
+	done
 }
 
 imds "$@"
diff --git a/lib/mdev/nvme-ebs-links b/lib/mdev/nvme-ebs-links
--- a/lib/mdev/nvme-ebs-links
+++ b/lib/mdev/nvme-ebs-links
@@ -1,8 +1,8 @@
 #!/bin/sh
-# vim:set ts=2 et:
+# vim:set ft=sh:
 
 # NOTE: The mdev-conf APK handles this now, but only for xvd or sd links (not
-#   both)
+#	 both)
 
 : "${LIBDIR:=$PREFIX/lib}"
 . "$LIBDIR/tiny-cloud/common"
@@ -11,39 +11,39 @@
 [ -x /usr/sbin/nvme ] || log crit "nvme cli not installed"
 
 raw_ebs_alias() {
-  /usr/sbin/nvme id-ctrl "/dev/$BASE" -b 2>/dev/null |
-    dd bs=32 skip=96 count=1 2>/dev/null
+	/usr/sbin/nvme id-ctrl "/dev/$BASE" -b 2>/dev/null |
+	dd bs=32 skip=96 count=1 2>/dev/null
 }
 
 case $ACTION in
-  add|"")
-    BASE=$(echo "$MDEV" | sed -re 's/^(nvme[0-9]+n[0-9]+).*/\1/')
-    PART=$(echo "$MDEV" | sed -re 's/nvme[0-9]+n[0-9]+p?//g')
-    # TODO: deadline instead of max tries
-    MAXTRY=30
-    TRY=0
-    until [ -n "$EBS" ]; do
-      EBS=$(raw_ebs_alias | sed -nre '/^(\/dev\/)?(s|xv)d[a-z]{1,2} /p' | tr -d ' ')
-      [ -n "$EBS" ] && break
-      TRY=$((TRY + 1))
-      if [ $TRY -eq $MAXTRY ]; then
-        log err "Failed to get EBS volume alias for $MDEV after $MAXTRY attempts ($(raw_ebs_alias))"
-        exit 1
-      fi
-      sleep 0.1
-    done
-    # remove any leading '/dev/', 'sd', or 'xvd', and append partition
-    EBS=${EBS#/dev/}
-    EBS=${EBS#sd}
-    EBS=${EBS#xvd}$PART
-    ln -sf "$MDEV" "sd$EBS" && log notice "Added sd$EBS symlink for $MDEV"
-    ln -sf "$MDEV" "xvd$EBS" && log notice "Added xvd$EBS symlink for $MDEV"
-    ;;
-  remove)
-    for TARGET in sd* xvd*
-    do
-      [ "$(readlink "$TARGET" 2>/dev/null)" = "$MDEV" ] && rm -f "$TARGET" && \
-        log notice "Removed $TARGET symlink for $MDEV"
-    done
-    ;;
+	add|"")
+	BASE=$(echo "$MDEV" | sed -re 's/^(nvme[0-9]+n[0-9]+).*/\1/')
+	PART=$(echo "$MDEV" | sed -re 's/nvme[0-9]+n[0-9]+p?//g')
+	# TODO: deadline instead of max tries
+	MAXTRY=30
+	TRY=0
+	until [ -n "$EBS" ]; do
+		EBS=$(raw_ebs_alias | sed -nre '/^(\/dev\/)?(s|xv)d[a-z]{1,2} /p' | tr -d ' ')
+		[ -n "$EBS" ] && break
+		TRY=$((TRY + 1))
+		if [ $TRY -eq $MAXTRY ]; then
+		log err "Failed to get EBS volume alias for $MDEV after $MAXTRY attempts ($(raw_ebs_alias))"
+		exit 1
+		fi
+		sleep 0.1
+	done
+	# remove any leading '/dev/', 'sd', or 'xvd', and append partition
+	EBS=${EBS#/dev/}
+	EBS=${EBS#sd}
+	EBS=${EBS#xvd}$PART
+	ln -sf "$MDEV" "sd$EBS" && log notice "Added sd$EBS symlink for $MDEV"
+	ln -sf "$MDEV" "xvd$EBS" && log notice "Added xvd$EBS symlink for $MDEV"
+	;;
+	remove)
+	for TARGET in sd* xvd*
+	do
+		[ "$(readlink "$TARGET" 2>/dev/null)" = "$MDEV" ] && rm -f "$TARGET" && \
+		log notice "Removed $TARGET symlink for $MDEV"
+	done
+	;;
 esac
diff --git a/lib/mdev/vnic-eth-hotplug b/lib/mdev/vnic-eth-hotplug
--- a/lib/mdev/vnic-eth-hotplug
+++ b/lib/mdev/vnic-eth-hotplug
@@ -1,5 +1,5 @@
 #!/bin/sh
-# vim:set ts=4 et:
+# vim:set ft=sh:
 
 set -e
 
@@ -7,52 +7,52 @@ set -e
 . "$LIBDIR/tiny-cloud/common"
 
 if [ -z "$MDEV" ] || [ -z "$ACTION" ]; then
-    log crit "MDEV or ACTION undefined, aborting"
+	log crit "MDEV or ACTION undefined, aborting"
 fi
 
 IFACE_CFG=/etc/network/interfaces
 
 ip() {
-    local v=-4 lev=info
-    if [ "$1" = '-4' ] || [ "$1" = '-6' ]; then
-        v="$1"
-        shift
-    fi
-    local op="$2"
+	local v=-4 lev=info
+	if [ "$1" = '-4' ] || [ "$1" = '-6' ]; then
+		v="$1"
+		shift
+	fi
+	local op="$2"
 
-    [ "$op" = show ] && lev=debug
-    if /sbin/ip "$v" "$@" || [ -n "$FAIL_OK" ]; then
-        log "$lev" "OK: ip $v $*"
-    else
-        log err "FAIL: ip $v $*"
-    fi
+	[ "$op" = show ] && lev=debug
+	if /sbin/ip "$v" "$@" || [ -n "$FAIL_OK" ]; then
+		log "$lev" "OK: ip $v $*"
+	else
+		log err "FAIL: ip $v $*"
+	fi
 }
 
 interface_up() {
-    log info "Bringing up $MDEV"
-    # umask so udhcpc PID file isn't non-owner writeable
-    (umask 0022 && ifup "$MDEV")
+	log info "Bringing up $MDEV"
+	# umask so udhcpc PID file isn't non-owner writeable
+	(umask 0022 && ifup "$MDEV")
 }
 
 cleanup_interface() {
-    local v pref rtable="${MDEV#eth}"
-    let rtable+=10000
+	local v pref rtable="${MDEV#eth}"
+	let rtable+=10000
 
-    log info "Cleaning up $MDEV"
+	log info "Cleaning up $MDEV"
 
-    # kill related udhcpc, don't panic if it's not there
-    kill "$(cat "/run/udhcpc.$MDEV.pid")" || true
+	# kill related udhcpc, don't panic if it's not there
+	kill "$(cat "/run/udhcpc.$MDEV.pid")" || true
 
-    # tidy up /run/ifstate, if it exists
-    [ -f /run/ifstate ] && sed -i -e "/^$MDEV=/d" /run/ifstate
-    rm -f /run/ifstate."$MDEV".lock
+	# tidy up /run/ifstate, if it exists
+	[ -f /run/ifstate ] && sed -i -e "/^$MDEV=/d" /run/ifstate
+	rm -f /run/ifstate."$MDEV".lock
 
-    # remove related rules
-    for v in 4 6; do
-        for pref in $(ip -"$v" rule show table "$rtable" | cut -d: -f1); do
-            ip -"$v" rule del pref "$pref"
-        done
-    done
+	# remove related rules
+	for v in 4 6; do
+		for pref in $(ip -"$v" rule show table "$rtable" | cut -d: -f1); do
+			ip -"$v" rule del pref "$pref"
+		done
+	done
 }
 
 is_networking_started() { service networking status -q 2>/dev/null; }
@@ -60,28 +60,28 @@ is_networking_started() { service networking status -q 2>/dev/null; }
 log info "STARTING: $ACTION $MDEV"
 
 if exec 200>>"$IFACE_CFG"; then
-    if flock 200; then
-        case $ACTION in
-            add|"")
-                assemble-interfaces
-                is_networking_started && interface_up
-                ;;
-            remove)
-                assemble-interfaces
-                is_networking_started && cleanup_interface
-                ;;
-            *)
-                log err "Unknown action '$ACTION'"
-                exit 1
-                ;;
-        esac
-    else
-        log err "Unable to flock $IFACE_CFG"
-        exit 1
-    fi
+	if flock 200; then
+		case $ACTION in
+			add|"")
+				assemble-interfaces
+				is_networking_started && interface_up
+				;;
+			remove)
+				assemble-interfaces
+				is_networking_started && cleanup_interface
+				;;
+			*)
+				log err "Unknown action '$ACTION'"
+				exit 1
+				;;
+		esac
+	else
+		log err "Unable to flock $IFACE_CFG"
+		exit 1
+	fi
 else
-    log err "Unable to assign fd 200 to flock $IFACE_CFG"
-    exit 1
+	log err "Unable to assign fd 200 to flock $IFACE_CFG"
+	exit 1
 fi
 
 log info "FINISHED: $ACTION $MDEV"
diff --git a/lib/tiny-cloud/cloud/nocloud/imds b/lib/tiny-cloud/cloud/nocloud/imds
--- a/lib/tiny-cloud/cloud/nocloud/imds
+++ b/lib/tiny-cloud/cloud/nocloud/imds
@@ -1,5 +1,5 @@
 # NoCloud Instance Metadata
-# vim: ts=4 et ft=sh:
+# vim:set ft=sh:
 # shellcheck shell=sh
 
 NOCLOUD_FILES="meta-data user-data vendor-data network-config"
@@ -7,100 +7,100 @@ NOCLOUD_FILES="meta-data user-data vendor-data network-config"
 is_nocloud_loaded() { [ -f "$TINY_CLOUD_VAR/.nocloud_loaded" ]; }
 
 _load_nocloud_cmdline() {
-    local kopt kv k v data
+	local kopt kv k v data
 
-    for kopt in $(cat "$ROOT/proc/cmdline" 2>/dev/null); do
-        echo "$kopt" | grep -qE '(^|=)ds=nocloud(-net)?;' || continue
-        for kv in $(echo "${kopt#*;}" | tr \; ' '); do
-            k=$(echo "$kv" | cut -d= -f1)
-            v=$(echo "$kv" | cut -d= -f2-)
-            case "$k" in
-                h|local-hostname)
-                    printf "\nlocal-hostname: %s" "$v" >> "$TINY_CLOUD_VAR/meta-data"
-                    ;;
-                i|instance-id)
-                    printf "\ninstance-id: %s" "$v" >> "$TINY_CLOUD_VAR/meta-data"
-                    ;;
-                s|seedfrom)
-                    for data in $NOCLOUD_FILES; do
-                        case "${v#file:/}" in
-                            /*)
-                                cat "$v/$data" >> "$TINY_CLOUD_VAR/$data" || continue
-                                echo >> "$TINY_CLOUD_VAR/$data"
-                                ;;
-                            http://*|https://*)
-                                wget -qO - "$v/$data" >> "$TINY_CLOUD_VAR/$data" || continue
-                                echo >> "$TINY_CLOUD_VAR/$data"
-                                ;;
-                            *) log -s warning "Unknown NoCloud seedfrom value '$v'"
-                                ;;
-                        esac
-                    done
-                    ;;
-                *)  log -s warning "Unknown NoCloud kernel cmdline key '$k'"
-                    ;;
-            esac
-        done
-        return
-    done
-    return 1
+	for kopt in $(cat "$ROOT/proc/cmdline" 2>/dev/null); do
+		echo "$kopt" | grep -qE '(^|=)ds=nocloud(-net)?;' || continue
+		for kv in $(echo "${kopt#*;}" | tr \; ' '); do
+			k=$(echo "$kv" | cut -d= -f1)
+			v=$(echo "$kv" | cut -d= -f2-)
+			case "$k" in
+				h|local-hostname)
+					printf "\nlocal-hostname: %s" "$v" >> "$TINY_CLOUD_VAR/meta-data"
+					;;
+				i|instance-id)
+					printf "\ninstance-id: %s" "$v" >> "$TINY_CLOUD_VAR/meta-data"
+					;;
+				s|seedfrom)
+					for data in $NOCLOUD_FILES; do
+						case "${v#file:/}" in
+							/*)
+								cat "$v/$data" >> "$TINY_CLOUD_VAR/$data" || continue
+								echo >> "$TINY_CLOUD_VAR/$data"
+								;;
+							http://*|https://*)
+								wget -qO - "$v/$data" >> "$TINY_CLOUD_VAR/$data" || continue
+								echo >> "$TINY_CLOUD_VAR/$data"
+								;;
+							*) log -s warning "Unknown NoCloud seedfrom value '$v'"
+								;;
+						esac
+					done
+					;;
+				*)  log -s warning "Unknown NoCloud kernel cmdline key '$k'"
+					;;
+			esac
+		done
+		return
+	done
+	return 1
 }
 
 _load_nocloud_volume() {
-    mkdir -p "$ROOT"/run/tiny-cloud
-    local mntdir=$(mktemp -d "$ROOT/run/tiny-cloud/cidata-XXXXXX")
-    local data mounted
+	mkdir -p "$ROOT"/run/tiny-cloud
+	local mntdir=$(mktemp -d "$ROOT/run/tiny-cloud/cidata-XXXXXX")
+	local data mounted
 
-    mkdir -p "$mntdir"
-    for fstype in vfat iso9660; do
-        [ "$mounted" ] && break
-        for label in cidata CIDATA; do
-            [ -n "$mounted" ] && break
-            mount -o ro -t "$fstype" LABEL="$label" "$mntdir" && mounted=1
-        done
-    done
-    if [ -n "$mounted" ]; then
-        for data in $NOCLOUD_FILES; do
-            # lack of source results in empty target
-            cat "$mntdir/$data" > "$TINY_CLOUD_VAR/$data" 2>/dev/null
-        done
-        umount "$mntdir"
-    else
-        return 1
-    fi
-    rmdir "$mntdir"
+	mkdir -p "$mntdir"
+	for fstype in vfat iso9660; do
+		[ "$mounted" ] && break
+		for label in cidata CIDATA; do
+			[ -n "$mounted" ] && break
+			mount -o ro -t "$fstype" LABEL="$label" "$mntdir" && mounted=1
+		done
+	done
+	if [ -n "$mounted" ]; then
+		for data in $NOCLOUD_FILES; do
+			# lack of source results in empty target
+			cat "$mntdir/$data" > "$TINY_CLOUD_VAR/$data" 2>/dev/null
+		done
+		umount "$mntdir"
+	else
+		return 1
+	fi
+	rmdir "$mntdir"
 }
 
 load_nocloud() {
-    # start with a clean slate
-    (cd "$TINY_CLOUD_VAR" && rm -f $NOCLOUD_FILES)
+	# start with a clean slate
+	(cd "$TINY_CLOUD_VAR" && rm -f $NOCLOUD_FILES)
 
-    if _load_nocloud_cmdline || _load_nocloud_volume; then
-        touch "$TINY_CLOUD_VAR/.nocloud_loaded"
-    else
-        log -s err "Unable to load NoCloud datasource"
-        return 1
-    fi
+	if _load_nocloud_cmdline || _load_nocloud_volume; then
+		touch "$TINY_CLOUD_VAR/.nocloud_loaded"
+	else
+		log -s err "Unable to load NoCloud datasource"
+		return 1
+	fi
 
-    # minimally, we expect some content in meta-data
-    [ -s "$TINY_CLOUD_VAR/meta-data" ] ||
-        log -s warning "NoCloud 'meta-data' is empty"
+	# minimally, we expect some content in meta-data
+	[ -s "$TINY_CLOUD_VAR/meta-data" ] ||
+		log -s warning "NoCloud 'meta-data' is empty"
 }
 
 _imds() {
-    mkdir -p "$TINY_CLOUD_VAR"
-    local file="$TINY_CLOUD_VAR/$(echo "$1" | cut -d/ -f1)"
-    local keypath="$(echo "$1" | cut -d/ -f2- | tr / ' ')"
+	mkdir -p "$TINY_CLOUD_VAR"
+	local file="$TINY_CLOUD_VAR/$(echo "$1" | cut -d/ -f1)"
+	local keypath="$(echo "$1" | cut -d/ -f2- | tr / ' ')"
 
-    is_nocloud_loaded || load_nocloud
+	is_nocloud_loaded || load_nocloud
 
-    # does file exist?
-    [ -f "$file" ] || return 1
+	# does file exist?
+	[ -f "$file" ] || return 1
 
-    # use 'file/' to get top-level keys
-    if [ $(basename "$file") = "$keypath" ]; then
-        cat "$file"
-    else
-        yx -f "$file" $keypath
-    fi
+	# use 'file/' to get top-level keys
+	if [ $(basename "$file") = "$keypath" ]; then
+		cat "$file"
+	else
+		yx -f "$file" $keypath
+	fi
 }
diff --git a/lib/tiny-cloud/init b/lib/tiny-cloud/init
--- a/lib/tiny-cloud/init
+++ b/lib/tiny-cloud/init
@@ -1,5 +1,5 @@
 # Tiny Cloud - Init Functions
-# vim:set ts=4 et ft=sh:
+# vim:set ft=sh:
 # shellcheck shell=sh
 
 # set defaults
@@ -12,18 +12,18 @@
 ### default phase actions (without leading 'init__')
 
 DEFAULT_ACTIONS_EARLY="
-    expand_root
-    install_hotplugs
-    set_default_interfaces
-    create_default_user
-    enable_sshd
+	expand_root
+	install_hotplugs
+	set_default_interfaces
+	create_default_user
+	enable_sshd
 "
 DEFAULT_ACTIONS_NET="
-    save_userdata
+	save_userdata
 "
 DEFAULT_ACTIONS_MAIN="
-    set_hostname
-    set_ssh_keys
+	set_hostname
+	set_ssh_keys
 "
 DEFAULT_ACTIONS_FINAL=""
 
@@ -40,236 +40,236 @@ DEFAULT_ACTIONS_FINAL=""
 ### standard init-early functions...
 
 init__expand_root() {
-    local dev=$(awk '$2 == "/" {print $1}' "$ROOT"/proc/mounts 2>/dev/null)
-    local filesystem=$(awk '$2 == "/" {print $3}' "$ROOT"/proc/mounts 2>/dev/null)
-    local partition=$(cat "$ROOT/sys/class/block/${dev#/dev/}/partition" 2>/dev/null)
+	local dev=$(awk '$2 == "/" {print $1}' "$ROOT"/proc/mounts 2>/dev/null)
+	local filesystem=$(awk '$2 == "/" {print $3}' "$ROOT"/proc/mounts 2>/dev/null)
+	local partition=$(cat "$ROOT/sys/class/block/${dev#/dev/}/partition" 2>/dev/null)
 
-    # only support ext2/ext3/ext4 for now
-    case "$filesystem" in
-        ext*) ;;
-        *) return;;
-    esac
+	# only support ext2/ext3/ext4 for now
+	case "$filesystem" in
+		ext*) ;;
+		*) return;;
+	esac
 
-    if [ -n "$partition" ]; then
-        # it's a partition, resize it
-        local volume=$(readlink -f "$ROOT/sys/class/block/${dev#/dev/}/..")
-        volume="/dev/${volume##*/}"
-        echo ", +" | $MOCK sfdisk -q --no-reread -N "$partition" "$volume"
-        $MOCK partx -u "$volume"
-    fi
-    # resize filesystem
-    $MOCK resize2fs "$dev"
+	if [ -n "$partition" ]; then
+		# it's a partition, resize it
+		local volume=$(readlink -f "$ROOT/sys/class/block/${dev#/dev/}/..")
+		volume="/dev/${volume##*/}"
+		echo ", +" | $MOCK sfdisk -q --no-reread -N "$partition" "$volume"
+		$MOCK partx -u "$volume"
+	fi
+	# resize filesystem
+	$MOCK resize2fs "$dev"
 }
 
 init__install_hotplugs() {
-    local level result rc=0
+	local level result rc=0
 
-    [ ! -n "$HOTPLUG_MODULES" ] && return
-    if [ -f "$LIBDIR/tiny-cloud/$HOTPLUG_TYPE" ]; then
-        . "$LIBDIR/tiny-cloud/$HOTPLUG_TYPE"
-    fi
+	[ ! -n "$HOTPLUG_MODULES" ] && return
+	if [ -f "$LIBDIR/tiny-cloud/$HOTPLUG_TYPE" ]; then
+		. "$LIBDIR/tiny-cloud/$HOTPLUG_TYPE"
+	fi
 
-    for module in $HOTPLUG_MODULES; do
-        result='unknown'
-        level='err'
-        printf "      >> " >&2
-        log -i -t "$phase/$ACTION" info "$module: installing"
-        if type "mod__$module" | grep -q -w "function"; then
-            if "mod__$module"; then
-                result='installed'
-                level='info'
-            else
-                result='failed'
-                rc=1
-            fi
-        fi
-        printf "      >> " >&2
-        log -i -t "$phase/$ACTION" info "$module: $result"
-    done
-    return $rc
+	for module in $HOTPLUG_MODULES; do
+		result='unknown'
+		level='err'
+		printf "	  >> " >&2
+		log -i -t "$phase/$ACTION" info "$module: installing"
+		if type "mod__$module" | grep -q -w "function"; then
+			if "mod__$module"; then
+				result='installed'
+				level='info'
+			else
+				result='failed'
+				rc=1
+			fi
+		fi
+		printf "	  >> " >&2
+		log -i -t "$phase/$ACTION" info "$module: $result"
+	done
+	return $rc
 }
 
 # collect ethernet interfaces, sorted by index
 ethernets() {
-    for i in "$ROOT/sys/class/net/"*; do
-        local iface="${i##*/}"
-        case "$iface" in
-            eth*) echo "$(cat "$i/ifindex") $iface";;
-        esac
-    done | sort -n | awk '{print $2}'
+	for i in "$ROOT/sys/class/net/"*; do
+		local iface="${i##*/}"
+		case "$iface" in
+			eth*) echo "$(cat "$i/ifindex") $iface";;
+		esac
+	done | sort -n | awk '{print $2}'
 }
 
 # find the interface that is has operstate up
 find_first_interface_up() {
-    local n=0
-    [ $# -eq 0 ] && return
-    while [ $n -le ${TINY_CLOUD_LINK_WAIT_MAX:-10} ]; do
-        for i in "$@"; do
-            if [ "$(cat "$ROOT/sys/class/net/$i/operstate")" = "up" ]; then
-                echo "$i"
-                return
-            fi
-        done
-        sleep 0.1
-        n=$((n+1))
-    done
+	local n=0
+	[ $# -eq 0 ] && return
+	while [ $n -le ${TINY_CLOUD_LINK_WAIT_MAX:-10} ]; do
+		for i in "$@"; do
+			if [ "$(cat "$ROOT/sys/class/net/$i/operstate")" = "up" ]; then
+				echo "$i"
+				return
+			fi
+		done
+		sleep 0.1
+		n=$((n+1))
+	done
 }
 
 # auto detect which network interface to auto configure
 # check which is connected or fallback to first
 # This will set link to down to all eth* except the found
 auto_detect_ethernet_interface() {
-    local ifaces="$(ethernets)"
-    [ -z "$ifaces" ] && return
+	local ifaces="$(ethernets)"
+	[ -z "$ifaces" ] && return
 
-    # find first connected interface
-    for i in $ifaces; do
-        $MOCK ip link set dev $i up >/dev/null
-    done
-    local iface="$(find_first_interface_up $ifaces)"
+	# find first connected interface
+	for i in $ifaces; do
+		$MOCK ip link set dev $i up >/dev/null
+	done
+	local iface="$(find_first_interface_up $ifaces)"
 
-    # use first if all are disconnected
-    if [ -z "$iface" ]; then
-        set -- $ifaces
-        iface="$1"
-    fi
+	# use first if all are disconnected
+	if [ -z "$iface" ]; then
+		set -- $ifaces
+		iface="$1"
+	fi
 
-    # we will use the found interface later so lets keep it up
-    for i in $ifaces; do
-        if [ "$i" != "$iface" ]; then
-            $MOCK ip link set dev $i down >/dev/null
-        fi
-    done
-    echo "$iface"
+	# we will use the found interface later so lets keep it up
+	for i in $ifaces; do
+		if [ "$i" != "$iface" ]; then
+			$MOCK ip link set dev $i down >/dev/null
+		fi
+	done
+	echo "$iface"
 }
 
 init__set_default_interfaces() {
-    if [ -f "$ROOT"/etc/network/interfaces ]; then
-        log -i -t "$phase" info "$ACTION: already set up"
-        return
-    fi
+	if [ -f "$ROOT"/etc/network/interfaces ]; then
+		log -i -t "$phase" info "$ACTION: already set up"
+		return
+	fi
 
-    mkdir -p "$ROOT/etc/network"
-    printf "%s\n%s\n\n" \
-        "auto lo" \
-        "iface lo inet loopback" \
-        > "$ROOT/etc/network/interfaces"
+	mkdir -p "$ROOT/etc/network"
+	printf "%s\n%s\n\n" \
+		"auto lo" \
+		"iface lo inet loopback" \
+		> "$ROOT/etc/network/interfaces"
 
-    local iface="$(auto_detect_ethernet_interface)"
-    if [ -z "$iface" ]; then
-        # TODO: message/log?
-        return
-    fi
-    printf "%s\n%s\n\t%s\n\n" \
-        "auto $iface" \
-        "iface $iface" \
-        "use dhcp"  >> "$ROOT/etc/network/interfaces"
+	local iface="$(auto_detect_ethernet_interface)"
+	if [ -z "$iface" ]; then
+		# TODO: message/log?
+		return
+	fi
+	printf "%s\n%s\n\t%s\n\n" \
+		"auto $iface" \
+		"iface $iface" \
+		"use dhcp"  >> "$ROOT/etc/network/interfaces"
 }
 
 init__create_default_user() {
-    local user="$CLOUD_USER"
-    # don't do anything if it already exists
-    if getent passwd "$user" >/dev/null; then
-        log -i -t "$phase" info "$ACTION: already exists"
-        return
-    fi
+	local user="$CLOUD_USER"
+	# don't do anything if it already exists
+	if getent passwd "$user" >/dev/null; then
+		log -i -t "$phase" info "$ACTION: already exists"
+		return
+	fi
 
-    $MOCK addgroup "$user"
-    $MOCK adduser -h "/home/$user" -s /bin/sh -G "$user" -D "$user"
-    $MOCK addgroup "$user" wheel
-    echo "$user:*" | $MOCK chpasswd -e
+	$MOCK addgroup "$user"
+	$MOCK adduser -h "/home/$user" -s /bin/sh -G "$user" -D "$user"
+	$MOCK addgroup "$user" wheel
+	echo "$user:*" | $MOCK chpasswd -e
 
-    # setup sudo and/or doas
-    if [ -d "$ROOT/etc/sudoers.d" ]; then
-        echo '%wheel ALL=(ALL) NOPASSWD: ALL' > "$ROOT/etc/sudoers.d/wheel"
-    fi
-    if [ -d "$ROOT/etc/doas.d" ]; then
-        echo 'permit nopass :wheel' > "$TARGET/etc/doas.d/wheel.conf"
-    fi
+	# setup sudo and/or doas
+	if [ -d "$ROOT/etc/sudoers.d" ]; then
+		echo '%wheel ALL=(ALL) NOPASSWD: ALL' > "$ROOT/etc/sudoers.d/wheel"
+	fi
+	if [ -d "$ROOT/etc/doas.d" ]; then
+		echo 'permit nopass :wheel' > "$TARGET/etc/doas.d/wheel.conf"
+	fi
 }
 
 init__enable_sshd() {
-    $MOCK rc-update add sshd default
-    # in case something else has enabled/disabled dservices
-    $MOCK rc-update --update
+	$MOCK rc-update add sshd default
+	# in case something else has enabled/disabled dservices
+	$MOCK rc-update --update
 }
 
 
 ### standard init-main functions
 
 init__set_hostname() {
-    local fqdn=$(imds @hostname)
-    if [ -z "$fqdn" ]; then
-        log -i -t "$phase" info "$ACTION: no hostname set"
-        return
-    fi
+	local fqdn=$(imds @hostname)
+	if [ -z "$fqdn" ]; then
+		log -i -t "$phase" info "$ACTION: no hostname set"
+		return
+	fi
 
-    local host="${fqdn%%\.*}"
-    if [ -z "$host" ]; then
-        log -i -t "$phase" warn "$ACTION: invalid hostname '$fqdn'"
-        return 1
-    fi
+	local host="${fqdn%%\.*}"
+	if [ -z "$host" ]; then
+		log -i -t "$phase" warn "$ACTION: invalid hostname '$fqdn'"
+		return 1
+	fi
 
-    mkdir -p "$ROOT"/etc
-    echo "$host" > "$ROOT"/etc/hostname
-    $MOCK hostname -F "$ROOT"/etc/hostname
-    echo -e "127.0.1.1\t$fqdn $host" >> "$ROOT"/etc/hosts
+	mkdir -p "$ROOT"/etc
+	echo "$host" > "$ROOT"/etc/hostname
+	$MOCK hostname -F "$ROOT"/etc/hostname
+	echo -e "127.0.1.1\t$fqdn $host" >> "$ROOT"/etc/hosts
 }
 
 init__set_ssh_keys() {
-    local sshkeys="$(imds @ssh-keys)"
-    if [ -z "$sshkeys" ]; then
-        log -i -t "$phase" info "$ACTION: no ssh key found"
-        return
-    fi
-    local user="$CLOUD_USER"
-    local pwent="$(getent passwd "$user")"
-    if [ -z "$pwent" ]; then
-        log -i -t "$phase" err "$ACTION: failed to find user $user"
-        return 1
-    fi
-    local group=$(echo "$pwent" | cut -d: -f4)
-    local ssh_dir="${ROOT}$(echo "$pwent" | cut -d: -f6)/.ssh"
-    local keys_file="$ssh_dir/authorized_keys"
+	local sshkeys="$(imds @ssh-keys)"
+	if [ -z "$sshkeys" ]; then
+		log -i -t "$phase" info "$ACTION: no ssh key found"
+		return
+	fi
+	local user="$CLOUD_USER"
+	local pwent="$(getent passwd "$user")"
+	if [ -z "$pwent" ]; then
+		log -i -t "$phase" err "$ACTION: failed to find user $user"
+		return 1
+	fi
+	local group=$(echo "$pwent" | cut -d: -f4)
+	local ssh_dir="${ROOT}$(echo "$pwent" | cut -d: -f6)/.ssh"
+	local keys_file="$ssh_dir/authorized_keys"
 
-    if [ ! -d "$ssh_dir" ]; then
-        mkdir -p "$ssh_dir"
-        chmod 700 "$ssh_dir"
-    fi
+	if [ ! -d "$ssh_dir" ]; then
+		mkdir -p "$ssh_dir"
+		chmod 700 "$ssh_dir"
+	fi
 
-    touch "$keys_file"
-    chmod 600 "$keys_file"
-    $MOCK chown -R "$user:$group" "$ssh_dir"
-    echo "$sshkeys" > "$keys_file"
+	touch "$keys_file"
+	chmod 600 "$keys_file"
+	$MOCK chown -R "$user:$group" "$ssh_dir"
+	echo "$sshkeys" > "$keys_file"
 }
 
 init__save_userdata() {
-    local userdata="$TINY_CLOUD_VAR/user-data"
-    if [ -f "$userdata" ]; then
-        log -i -t "$phase" info "$ACTION: user-data already saved"
-        return
-    fi
-    local tmpfile=$(mktemp "$userdata.XXXXXX")
+	local userdata="$TINY_CLOUD_VAR/user-data"
+	if [ -f "$userdata" ]; then
+		log -i -t "$phase" info "$ACTION: user-data already saved"
+		return
+	fi
+	local tmpfile=$(mktemp "$userdata.XXXXXX")
 
-    imds -e @userdata > "$tmpfile"
-    if printf '\037\213\010' | cmp -s -n 3 "$tmpfile"; then
-        gzip -dc "$tmpfile" > "$userdata"
-    elif printf 'BZh' | cmp -s -n 3 "$tmpfile"; then
-        bzip2 -dc "$tmpfile" > "$userdata"
-    elif printf '\375\067\172\130\132\000' | cmp -s -n 6 "$tmpfile"; then
-        unxz -c "$tmpfile" > "$userdata"
-    elif printf '\135\000\000' | cmp -s -n 3 "$tmpfile"; then
-        lzma -dc "$tmpfile" > "$userdata"
-    elif printf '\211\114\132' | cmp -s -n 3 "$tmpfile"; then
-        lzop -dc "$tmpfile" > "$userdata"
-    elif printf '\004\042\115\030' | cmp -s -n 4 "$tmpfile"; then
-        lz4 -dc "$tmpfile" > "$userdata"
-    elif printf '(\265/\375' | cmp -s -n 4 "$tmpfile"; then
-        zstd -dc "$tmpfile" > "$userdata"
-    else
-        cp "$tmpfile" "$userdata"
-    fi
-    rm "$tmpfile"
+	imds -e @userdata > "$tmpfile"
+	if printf '\037\213\010' | cmp -s -n 3 "$tmpfile"; then
+		gzip -dc "$tmpfile" > "$userdata"
+	elif printf 'BZh' | cmp -s -n 3 "$tmpfile"; then
+		bzip2 -dc "$tmpfile" > "$userdata"
+	elif printf '\375\067\172\130\132\000' | cmp -s -n 6 "$tmpfile"; then
+		unxz -c "$tmpfile" > "$userdata"
+	elif printf '\135\000\000' | cmp -s -n 3 "$tmpfile"; then
+		lzma -dc "$tmpfile" > "$userdata"
+	elif printf '\211\114\132' | cmp -s -n 3 "$tmpfile"; then
+		lzop -dc "$tmpfile" > "$userdata"
+	elif printf '\004\042\115\030' | cmp -s -n 4 "$tmpfile"; then
+		lz4 -dc "$tmpfile" > "$userdata"
+	elif printf '(\265/\375' | cmp -s -n 4 "$tmpfile"; then
+		zstd -dc "$tmpfile" > "$userdata"
+	else
+		cp "$tmpfile" "$userdata"
+	fi
+	rm "$tmpfile"
 }
 
 
@@ -279,26 +279,26 @@ init__save_userdata() {
 ### load cloud-specific init functions / vars (potentially overriding)
 
 if [ -f "$LIBDIR/tiny-cloud/cloud/$CLOUD/init" ]; then
-    . "$LIBDIR/tiny-cloud/cloud/$CLOUD/init"
+	. "$LIBDIR/tiny-cloud/cloud/$CLOUD/init"
 fi
 
 
 ### load user-data type-specific init functions / vars (potentially overriding)
 
 userdata_type() {
-    if [ ! -f "$TINY_CLOUD_VAR/user-data" ]; then
-        echo missing
-        return
-    fi
-    header=$(head -n1 "$TINY_CLOUD_VAR/user-data" | sed -e 's/[[:space:]].*//g')
-    case "$header" in
-        '#!'*)  echo script;;
-        '#'*)   echo ${header#\#};;
-        *)      echo unknown;;
-    esac
+	if [ ! -f "$TINY_CLOUD_VAR/user-data" ]; then
+		echo missing
+		return
+	fi
+	header=$(head -n1 "$TINY_CLOUD_VAR/user-data" | sed -e 's/[[:space:]].*//g')
+	case "$header" in
+		'#!'*)  echo script;;
+		'#'*)   echo ${header#\#};;
+		*)	  echo unknown;;
+	esac
 }
 
 USERDATA_TYPE="$(userdata_type)"
 if [ -f "$LIBDIR/tiny-cloud/user-data/$USERDATA_TYPE" ]; then
-    . "$LIBDIR/tiny-cloud/user-data/$USERDATA_TYPE"
+	. "$LIBDIR/tiny-cloud/user-data/$USERDATA_TYPE"
 fi
