move logic from init scripts to /lib/tiny-cloud/*

diff --git a/lib/tiny-cloud/imds b/lib/tiny-cloud/imds
--- a/lib/tiny-cloud/imds
+++ b/lib/tiny-cloud/imds
@@ -1,32 +1,33 @@
-# tiny-cloud Instance MetaData Service related functions and variables
+# Tiny Cloud - Instance MetaData Service functions and variables
 # vim:set ft=sh ts=4 noet:
 
-CONF_DIR="/etc/conf.d"
-LIB_DIR="/lib/tiny-cloud"
+### configuration
 
-### load configuration
-
-[ -f "$CONF_DIR"/tiny-cloud ] && source "$CONF_DIR"/tiny-cloud
-
-### configuration defaults
-
-CLOUD="${CLOUD:-unknown}"
-CLOUD_LOGIN="${CLOUD_LOGIN:-alpine}"
-if [ ! -d "$LIB_DIR/$CLOUD" ]; then
-	echo "ERROR: Unknown Cloud '$CLOUD'" >&2
-	exit 1
+if [ -z "$TINY_CLOUD_LIBS" ]; then
+    TINY_CLOUD_CONF=${TINY_CLOUD_CONF:-/etc/conf.d/tiny-cloud}
+    [ -f "$TINY_CLOUD_CONF" ] && source "$TINY_CLOUD_CONF"
+    TINY_CLOUD_LIBS=${TINY_CLOUD_LIBS:-/lib/tiny-cloud}
 fi
 
-IMDS_HEADER=
-IMDS_QUERY=
-IMDS_URL=
+# defaults
+CLOUD="${CLOUD:-unknown}"
 
-IMDS_HOSTNAME=
-IMDS_SSH_KEYS=
-IMDS_USERDATA=
+# these are always cloud-specific
 
-### default/common functions
+unset \
+	IMDS_HEADER	\
+	IMDS_QUERY \
+	IMDS_URL \
+	IMDS_HOSTNAME \
+	IMDS_SSH_KEYS \
+	IMDS_USERDATA
 
+unset -f \
+	_imds_token \
+	_imds_header \
+	2>/dev/null	|| true
+
+# without error reporting or ending newline enforcement
 _imds() {
 	wget --quiet --header "$(_imds_header)" --output-document - \
 		"$IMDS_URL/$1/$IMDS_QUERY"
@@ -55,6 +56,11 @@ imds_ssh_keys() {
 	imds "$IMDS_SSH_KEYS"
 }
 
-# cloud-specific things (potentially overriding the above)
+### load cloud-specific things
 
-[ -f "$LIB_DIR/$CLOUD/metadata" ] && source "$LIB_DIR/$CLOUD"/imds
+if [ ! -d "$TINY_CLOUD_LIBS/$CLOUD" ]; then
+	echo "ERROR: Unknown Cloud '$CLOUD'" >&2
+	exit 1
+fi
+
+source "$TINY_CLOUD_LIBS/$CLOUD/imds"
